version: "3"
services:
  nginx:
    restart: always
    container_name: nginx
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - /opt/webroot/thinkbim:/usr/share/nginx/html/thinkbim
      - /opt/server/thinkbim_nginx/logs:/var/log/nginx
      - /opt/server/thinkbim_nginx/cert:/etc/nginx/cert
      - /opt/server/thinkbim_nginx/conf.d:/etc/nginx/conf.d